spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/STOCK_AND_CAFE
  username: manager
  password: password

spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

